### ISSUE TITLE
Import Dependencies

### ISSUE THREAD

**Issue by firmai** [skfolio/skfolio#74]
Are there any reasons we are setting the import dependencies are set so high? For example, when installing `skfolio` alongside other libraries, it often leads to installation failures. Starting from Python 3.10, the following dependency specifications should work fine, adhering to minimal dependency versioning or minimal sufficient versioning. We can probably just test these to see if they work:

```toml
python = "^3.10"
numpy = ">=1.20"
pandas = ">=1.0"
plotly = ">=5.0"
scipy = ">=1.0"
scikit-learn = ">=1.0"
```
